// Code generated by ent, DO NOT EDIT.

package ordermain

import (
	"fmt"
)

const (
	// Label holds the string label denoting the ordermain type in the database.
	Label = "order_main"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderCode holds the string denoting the order_code field in the database.
	FieldOrderCode = "order_code"
	// FieldOrderStatus holds the string denoting the order_status field in the database.
	FieldOrderStatus = "order_status"
	// FieldExceptionType holds the string denoting the exception_type field in the database.
	FieldExceptionType = "exception_type"
	// FieldStoreOrderCode holds the string denoting the store_order_code field in the database.
	FieldStoreOrderCode = "store_order_code"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldShopName holds the string denoting the shop_name field in the database.
	FieldShopName = "shop_name"
	// FieldShipFirstName holds the string denoting the ship_first_name field in the database.
	FieldShipFirstName = "ship_first_name"
	// FieldShipLastName holds the string denoting the ship_last_name field in the database.
	FieldShipLastName = "ship_last_name"
	// FieldShipCompany holds the string denoting the ship_company field in the database.
	FieldShipCompany = "ship_company"
	// FieldShipStreet1 holds the string denoting the ship_street1 field in the database.
	FieldShipStreet1 = "ship_street1"
	// FieldShipStreet2 holds the string denoting the ship_street2 field in the database.
	FieldShipStreet2 = "ship_street2"
	// FieldShipCity holds the string denoting the ship_city field in the database.
	FieldShipCity = "ship_city"
	// FieldShipState holds the string denoting the ship_state field in the database.
	FieldShipState = "ship_state"
	// FieldShipZip holds the string denoting the ship_zip field in the database.
	FieldShipZip = "ship_zip"
	// FieldShipCountry holds the string denoting the ship_country field in the database.
	FieldShipCountry = "ship_country"
	// FieldShipCountryCode holds the string denoting the ship_country_code field in the database.
	FieldShipCountryCode = "ship_country_code"
	// FieldShipPhone holds the string denoting the ship_phone field in the database.
	FieldShipPhone = "ship_phone"
	// FieldShipFax holds the string denoting the ship_fax field in the database.
	FieldShipFax = "ship_fax"
	// FieldShipRemark holds the string denoting the ship_remark field in the database.
	FieldShipRemark = "ship_remark"
	// FieldShipHouse holds the string denoting the ship_house field in the database.
	FieldShipHouse = "ship_house"
	// FieldShipCertificateCode holds the string denoting the ship_certificate_code field in the database.
	FieldShipCertificateCode = "ship_certificate_code"
	// FieldOrderUserEmail holds the string denoting the order_user_email field in the database.
	FieldOrderUserEmail = "order_user_email"
	// FieldOrdersUserID holds the string denoting the orders_user_id field in the database.
	FieldOrdersUserID = "orders_user_id"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldCurrenciesID holds the string denoting the currencies_id field in the database.
	FieldCurrenciesID = "currencies_id"
	// FieldCurrencyRate holds the string denoting the currency_rate field in the database.
	FieldCurrencyRate = "currency_rate"
	// FieldShippingMethod holds the string denoting the shipping_method field in the database.
	FieldShippingMethod = "shipping_method"
	// FieldShippingMethodOrig holds the string denoting the shipping_method_orig field in the database.
	FieldShippingMethodOrig = "shipping_method_orig"
	// FieldShippingMethodName holds the string denoting the shipping_method_name field in the database.
	FieldShippingMethodName = "shipping_method_name"
	// FieldGrandTotal holds the string denoting the grand_total field in the database.
	FieldGrandTotal = "grand_total"
	// FieldTrackNumber holds the string denoting the track_number field in the database.
	FieldTrackNumber = "track_number"
	// FieldFollowNumber holds the string denoting the follow_number field in the database.
	FieldFollowNumber = "follow_number"
	// FieldDatePayment holds the string denoting the date_payment field in the database.
	FieldDatePayment = "date_payment"
	// FieldTransactionNumber holds the string denoting the transaction_number field in the database.
	FieldTransactionNumber = "transaction_number"
	// FieldTransactionFee holds the string denoting the transaction_fee field in the database.
	FieldTransactionFee = "transaction_fee"
	// FieldUpdateTrackTime holds the string denoting the update_track_time field in the database.
	FieldUpdateTrackTime = "update_track_time"
	// FieldUpdateFollowTime holds the string denoting the update_follow_time field in the database.
	FieldUpdateFollowTime = "update_follow_time"
	// FieldShippingCost holds the string denoting the shipping_cost field in the database.
	FieldShippingCost = "shipping_cost"
	// FieldShippingCostExt holds the string denoting the shipping_cost_ext field in the database.
	FieldShippingCostExt = "shipping_cost_ext"
	// FieldTaxesNumber holds the string denoting the taxes_number field in the database.
	FieldTaxesNumber = "taxes_number"
	// FieldTax holds the string denoting the tax field in the database.
	FieldTax = "tax"
	// FieldOrderDiscount holds the string denoting the order_discount field in the database.
	FieldOrderDiscount = "order_discount"
	// FieldInsurance holds the string denoting the insurance field in the database.
	FieldInsurance = "insurance"
	// FieldOrderWeight holds the string denoting the order_weight field in the database.
	FieldOrderWeight = "order_weight"
	// FieldOrderCretateType holds the string denoting the order_cretate_type field in the database.
	FieldOrderCretateType = "order_cretate_type"
	// FieldOrderType holds the string denoting the order_type field in the database.
	FieldOrderType = "order_type"
	// FieldStoreCreatedAt holds the string denoting the store_created_at field in the database.
	FieldStoreCreatedAt = "store_created_at"
	// FieldSubOrdersCode holds the string denoting the sub_orders_code field in the database.
	FieldSubOrdersCode = "sub_orders_code"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldWarehouseID holds the string denoting the warehouse_id field in the database.
	FieldWarehouseID = "warehouse_id"
	// FieldOrderListType holds the string denoting the order_list_type field in the database.
	FieldOrderListType = "order_list_type"
	// FieldOrderBatchNo holds the string denoting the order_batch_no field in the database.
	FieldOrderBatchNo = "order_batch_no"
	// FieldShopID holds the string denoting the shop_id field in the database.
	FieldShopID = "shop_id"
	// FieldSubtotal holds the string denoting the subtotal field in the database.
	FieldSubtotal = "subtotal"
	// FieldShippingFree holds the string denoting the shipping_free field in the database.
	FieldShippingFree = "shipping_free"
	// FieldOrderCost holds the string denoting the order_cost field in the database.
	FieldOrderCost = "order_cost"
	// FieldOrderProfit holds the string denoting the order_profit field in the database.
	FieldOrderProfit = "order_profit"
	// FieldShipDate holds the string denoting the ship_date field in the database.
	FieldShipDate = "ship_date"
	// FieldCommission holds the string denoting the commission field in the database.
	FieldCommission = "commission"
	// FieldInterceptState holds the string denoting the intercept_state field in the database.
	FieldInterceptState = "intercept_state"
	// FieldSendOrderTime holds the string denoting the send_order_time field in the database.
	FieldSendOrderTime = "send_order_time"
	// FieldSendOrderUser holds the string denoting the send_order_user field in the database.
	FieldSendOrderUser = "send_order_user"
	// FieldProviderType holds the string denoting the provider_type field in the database.
	FieldProviderType = "provider_type"
	// FieldOrderPackCost holds the string denoting the order_pack_cost field in the database.
	FieldOrderPackCost = "order_pack_cost"
	// FieldPaymentFixCost holds the string denoting the payment_fix_cost field in the database.
	FieldPaymentFixCost = "payment_fix_cost"
	// FieldIsFbaBehalf holds the string denoting the is_fba_behalf field in the database.
	FieldIsFbaBehalf = "is_fba_behalf"
	// FieldFulfillType holds the string denoting the fulfill_type field in the database.
	FieldFulfillType = "fulfill_type"
	// FieldFulfillException holds the string denoting the fulfill_exception field in the database.
	FieldFulfillException = "fulfill_exception"
	// FieldIossNumber holds the string denoting the ioss_number field in the database.
	FieldIossNumber = "ioss_number"
	// FieldWarehouseShopID holds the string denoting the warehouse_shop_id field in the database.
	FieldWarehouseShopID = "warehouse_shop_id"
	// FieldSalesRecordNumber holds the string denoting the sales_record_number field in the database.
	FieldSalesRecordNumber = "sales_record_number"
	// FieldTicketCode holds the string denoting the ticket_code field in the database.
	FieldTicketCode = "ticket_code"
	// FieldOverseasWarehouseStatus holds the string denoting the overseas_warehouse_status field in the database.
	FieldOverseasWarehouseStatus = "overseas_warehouse_status"
	// FieldPayPalID holds the string denoting the pay_pal_id field in the database.
	FieldPayPalID = "pay_pal_id"
	// FieldIsUpdate holds the string denoting the is_update field in the database.
	FieldIsUpdate = "is_update"
	// FieldOrderSaleState holds the string denoting the order_sale_state field in the database.
	FieldOrderSaleState = "order_sale_state"
	// FieldProductCost holds the string denoting the product_cost field in the database.
	FieldProductCost = "product_cost"
	// FieldHeadCost holds the string denoting the head_cost field in the database.
	FieldHeadCost = "head_cost"
	// FieldCarrierCode holds the string denoting the carrier_code field in the database.
	FieldCarrierCode = "carrier_code"
	// FieldWithheldTax holds the string denoting the withheld_tax field in the database.
	FieldWithheldTax = "withheld_tax"
	// FieldOtherFee holds the string denoting the other_fee field in the database.
	FieldOtherFee = "other_fee"
	// FieldEscrowTax holds the string denoting the escrow_tax field in the database.
	FieldEscrowTax = "escrow_tax"
	// FieldFinalProductVatTax holds the string denoting the final_product_vat_tax field in the database.
	FieldFinalProductVatTax = "final_product_vat_tax"
	// FieldFinalShippingVatTax holds the string denoting the final_shipping_vat_tax field in the database.
	FieldFinalShippingVatTax = "final_shipping_vat_tax"
	// FieldShippingCharge holds the string denoting the shipping_charge field in the database.
	FieldShippingCharge = "shipping_charge"
	// FieldVoucherPlatform holds the string denoting the voucher_platform field in the database.
	FieldVoucherPlatform = "voucher_platform"
	// FieldOverTimeLeft holds the string denoting the over_time_left field in the database.
	FieldOverTimeLeft = "over_time_left"
	// FieldShippingRebate holds the string denoting the shipping_rebate field in the database.
	FieldShippingRebate = "shipping_rebate"
	// FieldLabelList holds the string denoting the label_list field in the database.
	FieldLabelList = "label_list"
	// FieldOutRealGrandTotal holds the string denoting the out_real_grand_total field in the database.
	FieldOutRealGrandTotal = "out_real_grand_total"
	// FieldBillList holds the string denoting the bill_list field in the database.
	FieldBillList = "bill_list"
	// FieldOutGrandTotal holds the string denoting the out_grand_total field in the database.
	FieldOutGrandTotal = "out_grand_total"
	// FieldDeliverShop holds the string denoting the deliver_shop field in the database.
	FieldDeliverShop = "deliver_shop"
	// FieldShippingCostFinal holds the string denoting the shipping_cost_final field in the database.
	FieldShippingCostFinal = "shipping_cost_final"
	// FieldShippingFreeAbout holds the string denoting the shipping_free_about field in the database.
	FieldShippingFreeAbout = "shipping_free_about"
	// FieldCreateOrderStatus holds the string denoting the create_order_status field in the database.
	FieldCreateOrderStatus = "create_order_status"
	// FieldFinanceTime holds the string denoting the finance_time field in the database.
	FieldFinanceTime = "finance_time"
	// FieldIsQcc holds the string denoting the is_qcc field in the database.
	FieldIsQcc = "is_qcc"
	// FieldRejectReason holds the string denoting the reject_reason field in the database.
	FieldRejectReason = "reject_reason"
	// FieldOrderLocalTime holds the string denoting the order_local_time field in the database.
	FieldOrderLocalTime = "order_local_time"
	// FieldDiscountCode holds the string denoting the discount_code field in the database.
	FieldDiscountCode = "discount_code"
	// FieldStockoutStatus holds the string denoting the stockout_status field in the database.
	FieldStockoutStatus = "stockout_status"
	// FieldOrderLength holds the string denoting the order_length field in the database.
	FieldOrderLength = "order_length"
	// FieldOrderWidth holds the string denoting the order_width field in the database.
	FieldOrderWidth = "order_width"
	// FieldOrderHeight holds the string denoting the order_height field in the database.
	FieldOrderHeight = "order_height"
	// FieldFirstSide holds the string denoting the first_side field in the database.
	FieldFirstSide = "first_side"
	// FieldSecondSide holds the string denoting the second_side field in the database.
	FieldSecondSide = "second_side"
	// FieldThirdSide holds the string denoting the third_side field in the database.
	FieldThirdSide = "third_side"
	// FieldOrderFeeWeight holds the string denoting the order_fee_weight field in the database.
	FieldOrderFeeWeight = "order_fee_weight"
	// FieldShopManager holds the string denoting the shop_manager field in the database.
	FieldShopManager = "shop_manager"
	// FieldPushStatus holds the string denoting the push_status field in the database.
	FieldPushStatus = "push_status"
	// FieldBuyerPaidShippingFee holds the string denoting the buyer_paid_shipping_fee field in the database.
	FieldBuyerPaidShippingFee = "buyer_paid_shipping_fee"
	// Table holds the table name of the ordermain in the database.
	Table = "order_mains"
)

// Columns holds all SQL columns for ordermain fields.
var Columns = []string{
	FieldID,
	FieldOrderCode,
	FieldOrderStatus,
	FieldExceptionType,
	FieldStoreOrderCode,
	FieldPlatform,
	FieldShopName,
	FieldShipFirstName,
	FieldShipLastName,
	FieldShipCompany,
	FieldShipStreet1,
	FieldShipStreet2,
	FieldShipCity,
	FieldShipState,
	FieldShipZip,
	FieldShipCountry,
	FieldShipCountryCode,
	FieldShipPhone,
	FieldShipFax,
	FieldShipRemark,
	FieldShipHouse,
	FieldShipCertificateCode,
	FieldOrderUserEmail,
	FieldOrdersUserID,
	FieldCurrency,
	FieldCurrenciesID,
	FieldCurrencyRate,
	FieldShippingMethod,
	FieldShippingMethodOrig,
	FieldShippingMethodName,
	FieldGrandTotal,
	FieldTrackNumber,
	FieldFollowNumber,
	FieldDatePayment,
	FieldTransactionNumber,
	FieldTransactionFee,
	FieldUpdateTrackTime,
	FieldUpdateFollowTime,
	FieldShippingCost,
	FieldShippingCostExt,
	FieldTaxesNumber,
	FieldTax,
	FieldOrderDiscount,
	FieldInsurance,
	FieldOrderWeight,
	FieldOrderCretateType,
	FieldOrderType,
	FieldStoreCreatedAt,
	FieldSubOrdersCode,
	FieldUpdatedAt,
	FieldCreatedAt,
	FieldWarehouseID,
	FieldOrderListType,
	FieldOrderBatchNo,
	FieldShopID,
	FieldSubtotal,
	FieldShippingFree,
	FieldOrderCost,
	FieldOrderProfit,
	FieldShipDate,
	FieldCommission,
	FieldInterceptState,
	FieldSendOrderTime,
	FieldSendOrderUser,
	FieldProviderType,
	FieldOrderPackCost,
	FieldPaymentFixCost,
	FieldIsFbaBehalf,
	FieldFulfillType,
	FieldFulfillException,
	FieldIossNumber,
	FieldWarehouseShopID,
	FieldSalesRecordNumber,
	FieldTicketCode,
	FieldOverseasWarehouseStatus,
	FieldPayPalID,
	FieldIsUpdate,
	FieldOrderSaleState,
	FieldProductCost,
	FieldHeadCost,
	FieldCarrierCode,
	FieldWithheldTax,
	FieldOtherFee,
	FieldEscrowTax,
	FieldFinalProductVatTax,
	FieldFinalShippingVatTax,
	FieldShippingCharge,
	FieldVoucherPlatform,
	FieldOverTimeLeft,
	FieldShippingRebate,
	FieldLabelList,
	FieldOutRealGrandTotal,
	FieldBillList,
	FieldOutGrandTotal,
	FieldDeliverShop,
	FieldShippingCostFinal,
	FieldShippingFreeAbout,
	FieldCreateOrderStatus,
	FieldFinanceTime,
	FieldIsQcc,
	FieldRejectReason,
	FieldOrderLocalTime,
	FieldDiscountCode,
	FieldStockoutStatus,
	FieldOrderLength,
	FieldOrderWidth,
	FieldOrderHeight,
	FieldFirstSide,
	FieldSecondSide,
	FieldThirdSide,
	FieldOrderFeeWeight,
	FieldShopManager,
	FieldPushStatus,
	FieldBuyerPaidShippingFee,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOrderCode holds the default value on creation for the "order_code" field.
	DefaultOrderCode string
	// DefaultOrderStatus holds the default value on creation for the "order_status" field.
	DefaultOrderStatus int8
	// DefaultStoreOrderCode holds the default value on creation for the "store_order_code" field.
	DefaultStoreOrderCode string
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// DefaultShopName holds the default value on creation for the "shop_name" field.
	DefaultShopName string
	// DefaultShipFirstName holds the default value on creation for the "ship_first_name" field.
	DefaultShipFirstName string
	// DefaultShipLastName holds the default value on creation for the "ship_last_name" field.
	DefaultShipLastName string
	// DefaultShipCompany holds the default value on creation for the "ship_company" field.
	DefaultShipCompany string
	// DefaultShipStreet1 holds the default value on creation for the "ship_street1" field.
	DefaultShipStreet1 string
	// DefaultShipStreet2 holds the default value on creation for the "ship_street2" field.
	DefaultShipStreet2 string
	// DefaultShipCity holds the default value on creation for the "ship_city" field.
	DefaultShipCity string
	// DefaultShipState holds the default value on creation for the "ship_state" field.
	DefaultShipState string
	// DefaultShipZip holds the default value on creation for the "ship_zip" field.
	DefaultShipZip string
	// DefaultShipCountry holds the default value on creation for the "ship_country" field.
	DefaultShipCountry string
	// DefaultShipCountryCode holds the default value on creation for the "ship_country_code" field.
	DefaultShipCountryCode string
	// DefaultShipPhone holds the default value on creation for the "ship_phone" field.
	DefaultShipPhone string
	// DefaultShipFax holds the default value on creation for the "ship_fax" field.
	DefaultShipFax string
	// DefaultShipRemark holds the default value on creation for the "ship_remark" field.
	DefaultShipRemark string
	// DefaultShipHouse holds the default value on creation for the "ship_house" field.
	DefaultShipHouse string
	// DefaultShipCertificateCode holds the default value on creation for the "ship_certificate_code" field.
	DefaultShipCertificateCode string
	// DefaultOrderUserEmail holds the default value on creation for the "order_user_email" field.
	DefaultOrderUserEmail string
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultCurrenciesID holds the default value on creation for the "currencies_id" field.
	DefaultCurrenciesID int32
	// DefaultCurrencyRate holds the default value on creation for the "currency_rate" field.
	DefaultCurrencyRate float64
	// DefaultShippingMethod holds the default value on creation for the "shipping_method" field.
	DefaultShippingMethod string
	// DefaultShippingMethodOrig holds the default value on creation for the "shipping_method_orig" field.
	DefaultShippingMethodOrig string
	// DefaultShippingMethodName holds the default value on creation for the "shipping_method_name" field.
	DefaultShippingMethodName string
	// DefaultGrandTotal holds the default value on creation for the "grand_total" field.
	DefaultGrandTotal float64
	// DefaultTrackNumber holds the default value on creation for the "track_number" field.
	DefaultTrackNumber string
	// DefaultFollowNumber holds the default value on creation for the "follow_number" field.
	DefaultFollowNumber string
	// DefaultTransactionNumber holds the default value on creation for the "transaction_number" field.
	DefaultTransactionNumber string
	// DefaultTransactionFee holds the default value on creation for the "transaction_fee" field.
	DefaultTransactionFee float64
	// DefaultShippingCost holds the default value on creation for the "shipping_cost" field.
	DefaultShippingCost float64
	// DefaultShippingCostExt holds the default value on creation for the "shipping_cost_ext" field.
	DefaultShippingCostExt float64
	// DefaultTaxesNumber holds the default value on creation for the "taxes_number" field.
	DefaultTaxesNumber string
	// DefaultTax holds the default value on creation for the "tax" field.
	DefaultTax float64
	// DefaultOrderDiscount holds the default value on creation for the "order_discount" field.
	DefaultOrderDiscount float64
	// DefaultInsurance holds the default value on creation for the "insurance" field.
	DefaultInsurance float64
	// DefaultOrderWeight holds the default value on creation for the "order_weight" field.
	DefaultOrderWeight float64
	// DefaultOrderType holds the default value on creation for the "order_type" field.
	DefaultOrderType int8
	// DefaultSubOrdersCode holds the default value on creation for the "sub_orders_code" field.
	DefaultSubOrdersCode string
	// DefaultWarehouseID holds the default value on creation for the "warehouse_id" field.
	DefaultWarehouseID string
	// DefaultOrderListType holds the default value on creation for the "order_list_type" field.
	DefaultOrderListType int8
	// DefaultOrderBatchNo holds the default value on creation for the "order_batch_no" field.
	DefaultOrderBatchNo string
	// DefaultShopID holds the default value on creation for the "shop_id" field.
	DefaultShopID int32
	// DefaultOrderCost holds the default value on creation for the "order_cost" field.
	DefaultOrderCost float64
	// DefaultOrderProfit holds the default value on creation for the "order_profit" field.
	DefaultOrderProfit float64
	// DefaultCommission holds the default value on creation for the "commission" field.
	DefaultCommission float64
	// DefaultInterceptState holds the default value on creation for the "intercept_state" field.
	DefaultInterceptState int8
	// DefaultProviderType holds the default value on creation for the "provider_type" field.
	DefaultProviderType int8
	// DefaultOrderPackCost holds the default value on creation for the "order_pack_cost" field.
	DefaultOrderPackCost float64
	// DefaultPaymentFixCost holds the default value on creation for the "payment_fix_cost" field.
	DefaultPaymentFixCost float64
	// DefaultIsFbaBehalf holds the default value on creation for the "is_fba_behalf" field.
	DefaultIsFbaBehalf int8
	// DefaultFulfillType holds the default value on creation for the "fulfill_type" field.
	DefaultFulfillType int8
	// DefaultFulfillException holds the default value on creation for the "fulfill_exception" field.
	DefaultFulfillException int8
	// DefaultIossNumber holds the default value on creation for the "ioss_number" field.
	DefaultIossNumber string
	// DefaultSalesRecordNumber holds the default value on creation for the "sales_record_number" field.
	DefaultSalesRecordNumber string
	// DefaultTicketCode holds the default value on creation for the "ticket_code" field.
	DefaultTicketCode string
	// DefaultOverseasWarehouseStatus holds the default value on creation for the "overseas_warehouse_status" field.
	DefaultOverseasWarehouseStatus string
	// DefaultPayPalID holds the default value on creation for the "pay_pal_id" field.
	DefaultPayPalID string
	// DefaultIsUpdate holds the default value on creation for the "is_update" field.
	DefaultIsUpdate int8
	// DefaultOrderSaleState holds the default value on creation for the "order_sale_state" field.
	DefaultOrderSaleState int8
	// DefaultProductCost holds the default value on creation for the "product_cost" field.
	DefaultProductCost float64
	// DefaultHeadCost holds the default value on creation for the "head_cost" field.
	DefaultHeadCost float64
	// DefaultCarrierCode holds the default value on creation for the "carrier_code" field.
	DefaultCarrierCode string
	// DefaultWithheldTax holds the default value on creation for the "withheld_tax" field.
	DefaultWithheldTax float64
	// DefaultOtherFee holds the default value on creation for the "other_fee" field.
	DefaultOtherFee float64
	// DefaultEscrowTax holds the default value on creation for the "escrow_tax" field.
	DefaultEscrowTax float64
	// DefaultFinalProductVatTax holds the default value on creation for the "final_product_vat_tax" field.
	DefaultFinalProductVatTax float64
	// DefaultFinalShippingVatTax holds the default value on creation for the "final_shipping_vat_tax" field.
	DefaultFinalShippingVatTax float64
	// DefaultShippingCharge holds the default value on creation for the "shipping_charge" field.
	DefaultShippingCharge float64
	// DefaultVoucherPlatform holds the default value on creation for the "voucher_platform" field.
	DefaultVoucherPlatform float64
	// DefaultShippingRebate holds the default value on creation for the "shipping_rebate" field.
	DefaultShippingRebate float64
	// DefaultLabelList holds the default value on creation for the "label_list" field.
	DefaultLabelList string
	// DefaultOutRealGrandTotal holds the default value on creation for the "out_real_grand_total" field.
	DefaultOutRealGrandTotal float64
	// DefaultBillList holds the default value on creation for the "bill_list" field.
	DefaultBillList string
	// DefaultOutGrandTotal holds the default value on creation for the "out_grand_total" field.
	DefaultOutGrandTotal float64
	// DefaultDeliverShop holds the default value on creation for the "deliver_shop" field.
	DefaultDeliverShop string
	// DefaultShippingCostFinal holds the default value on creation for the "shipping_cost_final" field.
	DefaultShippingCostFinal float64
	// DefaultShippingFreeAbout holds the default value on creation for the "shipping_free_about" field.
	DefaultShippingFreeAbout float64
	// DefaultCreateOrderStatus holds the default value on creation for the "create_order_status" field.
	DefaultCreateOrderStatus int8
	// DefaultIsQcc holds the default value on creation for the "is_qcc" field.
	DefaultIsQcc int8
	// DefaultRejectReason holds the default value on creation for the "reject_reason" field.
	DefaultRejectReason string
	// DefaultDiscountCode holds the default value on creation for the "discount_code" field.
	DefaultDiscountCode string
	// DefaultStockoutStatus holds the default value on creation for the "stockout_status" field.
	DefaultStockoutStatus int8
	// DefaultOrderLength holds the default value on creation for the "order_length" field.
	DefaultOrderLength float64
	// DefaultOrderWidth holds the default value on creation for the "order_width" field.
	DefaultOrderWidth float64
	// DefaultOrderHeight holds the default value on creation for the "order_height" field.
	DefaultOrderHeight float64
	// DefaultFirstSide holds the default value on creation for the "first_side" field.
	DefaultFirstSide float64
	// DefaultSecondSide holds the default value on creation for the "second_side" field.
	DefaultSecondSide float64
	// DefaultThirdSide holds the default value on creation for the "third_side" field.
	DefaultThirdSide float64
	// DefaultOrderFeeWeight holds the default value on creation for the "order_fee_weight" field.
	DefaultOrderFeeWeight float64
	// DefaultShopManager holds the default value on creation for the "shop_manager" field.
	DefaultShopManager string
	// DefaultPushStatus holds the default value on creation for the "push_status" field.
	DefaultPushStatus int8
)

// OrderCretateType defines the type for the "order_cretate_type" enum field.
type OrderCretateType string

// OrderCretateTypeDownload is the default value of the OrderCretateType enum.
const DefaultOrderCretateType = OrderCretateTypeDownload

// OrderCretateType values.
const (
	OrderCretateTypeCreate   OrderCretateType = "create"
	OrderCretateTypeDownload OrderCretateType = "download"
)

func (oct OrderCretateType) String() string {
	return string(oct)
}

// OrderCretateTypeValidator is a validator for the "order_cretate_type" field enum values. It is called by the builders before save.
func OrderCretateTypeValidator(oct OrderCretateType) error {
	switch oct {
	case OrderCretateTypeCreate, OrderCretateTypeDownload:
		return nil
	default:
		return fmt.Errorf("ordermain: invalid enum value for order_cretate_type field: %q", oct)
	}
}
