// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"order/ent/ordermain"
	"order/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderMainQuery is the builder for querying OrderMain entities.
type OrderMainQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.OrderMain
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrderMainQuery builder.
func (omq *OrderMainQuery) Where(ps ...predicate.OrderMain) *OrderMainQuery {
	omq.predicates = append(omq.predicates, ps...)
	return omq
}

// Limit adds a limit step to the query.
func (omq *OrderMainQuery) Limit(limit int) *OrderMainQuery {
	omq.limit = &limit
	return omq
}

// Offset adds an offset step to the query.
func (omq *OrderMainQuery) Offset(offset int) *OrderMainQuery {
	omq.offset = &offset
	return omq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (omq *OrderMainQuery) Unique(unique bool) *OrderMainQuery {
	omq.unique = &unique
	return omq
}

// Order adds an order step to the query.
func (omq *OrderMainQuery) Order(o ...OrderFunc) *OrderMainQuery {
	omq.order = append(omq.order, o...)
	return omq
}

// First returns the first OrderMain entity from the query.
// Returns a *NotFoundError when no OrderMain was found.
func (omq *OrderMainQuery) First(ctx context.Context) (*OrderMain, error) {
	nodes, err := omq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ordermain.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (omq *OrderMainQuery) FirstX(ctx context.Context) *OrderMain {
	node, err := omq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrderMain ID from the query.
// Returns a *NotFoundError when no OrderMain ID was found.
func (omq *OrderMainQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = omq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ordermain.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (omq *OrderMainQuery) FirstIDX(ctx context.Context) int32 {
	id, err := omq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrderMain entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrderMain entity is found.
// Returns a *NotFoundError when no OrderMain entities are found.
func (omq *OrderMainQuery) Only(ctx context.Context) (*OrderMain, error) {
	nodes, err := omq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ordermain.Label}
	default:
		return nil, &NotSingularError{ordermain.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (omq *OrderMainQuery) OnlyX(ctx context.Context) *OrderMain {
	node, err := omq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrderMain ID in the query.
// Returns a *NotSingularError when more than one OrderMain ID is found.
// Returns a *NotFoundError when no entities are found.
func (omq *OrderMainQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = omq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ordermain.Label}
	default:
		err = &NotSingularError{ordermain.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (omq *OrderMainQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := omq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrderMains.
func (omq *OrderMainQuery) All(ctx context.Context) ([]*OrderMain, error) {
	if err := omq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return omq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (omq *OrderMainQuery) AllX(ctx context.Context) []*OrderMain {
	nodes, err := omq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrderMain IDs.
func (omq *OrderMainQuery) IDs(ctx context.Context) ([]int32, error) {
	var ids []int32
	if err := omq.Select(ordermain.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (omq *OrderMainQuery) IDsX(ctx context.Context) []int32 {
	ids, err := omq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (omq *OrderMainQuery) Count(ctx context.Context) (int, error) {
	if err := omq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return omq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (omq *OrderMainQuery) CountX(ctx context.Context) int {
	count, err := omq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (omq *OrderMainQuery) Exist(ctx context.Context) (bool, error) {
	if err := omq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return omq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (omq *OrderMainQuery) ExistX(ctx context.Context) bool {
	exist, err := omq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrderMainQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (omq *OrderMainQuery) Clone() *OrderMainQuery {
	if omq == nil {
		return nil
	}
	return &OrderMainQuery{
		config:     omq.config,
		limit:      omq.limit,
		offset:     omq.offset,
		order:      append([]OrderFunc{}, omq.order...),
		predicates: append([]predicate.OrderMain{}, omq.predicates...),
		// clone intermediate query.
		sql:    omq.sql.Clone(),
		path:   omq.path,
		unique: omq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrderCode string `json:"order_code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrderMain.Query().
//		GroupBy(ordermain.FieldOrderCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (omq *OrderMainQuery) GroupBy(field string, fields ...string) *OrderMainGroupBy {
	grbuild := &OrderMainGroupBy{config: omq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := omq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return omq.sqlQuery(ctx), nil
	}
	grbuild.label = ordermain.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrderCode string `json:"order_code,omitempty"`
//	}
//
//	client.OrderMain.Query().
//		Select(ordermain.FieldOrderCode).
//		Scan(ctx, &v)
//
func (omq *OrderMainQuery) Select(fields ...string) *OrderMainSelect {
	omq.fields = append(omq.fields, fields...)
	selbuild := &OrderMainSelect{OrderMainQuery: omq}
	selbuild.label = ordermain.Label
	selbuild.flds, selbuild.scan = &omq.fields, selbuild.Scan
	return selbuild
}

func (omq *OrderMainQuery) prepareQuery(ctx context.Context) error {
	for _, f := range omq.fields {
		if !ordermain.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if omq.path != nil {
		prev, err := omq.path(ctx)
		if err != nil {
			return err
		}
		omq.sql = prev
	}
	return nil
}

func (omq *OrderMainQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrderMain, error) {
	var (
		nodes = []*OrderMain{}
		_spec = omq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*OrderMain).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &OrderMain{config: omq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, omq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (omq *OrderMainQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := omq.querySpec()
	_spec.Node.Columns = omq.fields
	if len(omq.fields) > 0 {
		_spec.Unique = omq.unique != nil && *omq.unique
	}
	return sqlgraph.CountNodes(ctx, omq.driver, _spec)
}

func (omq *OrderMainQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := omq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (omq *OrderMainQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ordermain.Table,
			Columns: ordermain.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: ordermain.FieldID,
			},
		},
		From:   omq.sql,
		Unique: true,
	}
	if unique := omq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := omq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ordermain.FieldID)
		for i := range fields {
			if fields[i] != ordermain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := omq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := omq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := omq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := omq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (omq *OrderMainQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(omq.driver.Dialect())
	t1 := builder.Table(ordermain.Table)
	columns := omq.fields
	if len(columns) == 0 {
		columns = ordermain.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if omq.sql != nil {
		selector = omq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if omq.unique != nil && *omq.unique {
		selector.Distinct()
	}
	for _, p := range omq.predicates {
		p(selector)
	}
	for _, p := range omq.order {
		p(selector)
	}
	if offset := omq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := omq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrderMainGroupBy is the group-by builder for OrderMain entities.
type OrderMainGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (omgb *OrderMainGroupBy) Aggregate(fns ...AggregateFunc) *OrderMainGroupBy {
	omgb.fns = append(omgb.fns, fns...)
	return omgb
}

// Scan applies the group-by query and scans the result into the given value.
func (omgb *OrderMainGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := omgb.path(ctx)
	if err != nil {
		return err
	}
	omgb.sql = query
	return omgb.sqlScan(ctx, v)
}

func (omgb *OrderMainGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range omgb.fields {
		if !ordermain.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := omgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := omgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (omgb *OrderMainGroupBy) sqlQuery() *sql.Selector {
	selector := omgb.sql.Select()
	aggregation := make([]string, 0, len(omgb.fns))
	for _, fn := range omgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(omgb.fields)+len(omgb.fns))
		for _, f := range omgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(omgb.fields...)...)
}

// OrderMainSelect is the builder for selecting fields of OrderMain entities.
type OrderMainSelect struct {
	*OrderMainQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (oms *OrderMainSelect) Scan(ctx context.Context, v interface{}) error {
	if err := oms.prepareQuery(ctx); err != nil {
		return err
	}
	oms.sql = oms.OrderMainQuery.sqlQuery(ctx)
	return oms.sqlScan(ctx, v)
}

func (oms *OrderMainSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := oms.sql.Query()
	if err := oms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
