// Code generated by ent, DO NOT EDIT.

package ent

import (
	"order/ent/ordermain"
	"order/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	ordermainFields := schema.OrderMain{}.Fields()
	_ = ordermainFields
	// ordermainDescOrderCode is the schema descriptor for order_code field.
	ordermainDescOrderCode := ordermainFields[1].Descriptor()
	// ordermain.DefaultOrderCode holds the default value on creation for the order_code field.
	ordermain.DefaultOrderCode = ordermainDescOrderCode.Default.(string)
	// ordermainDescOrderStatus is the schema descriptor for order_status field.
	ordermainDescOrderStatus := ordermainFields[2].Descriptor()
	// ordermain.DefaultOrderStatus holds the default value on creation for the order_status field.
	ordermain.DefaultOrderStatus = ordermainDescOrderStatus.Default.(int8)
	// ordermainDescStoreOrderCode is the schema descriptor for store_order_code field.
	ordermainDescStoreOrderCode := ordermainFields[4].Descriptor()
	// ordermain.DefaultStoreOrderCode holds the default value on creation for the store_order_code field.
	ordermain.DefaultStoreOrderCode = ordermainDescStoreOrderCode.Default.(string)
	// ordermainDescPlatform is the schema descriptor for platform field.
	ordermainDescPlatform := ordermainFields[5].Descriptor()
	// ordermain.DefaultPlatform holds the default value on creation for the platform field.
	ordermain.DefaultPlatform = ordermainDescPlatform.Default.(string)
	// ordermainDescShopName is the schema descriptor for shop_name field.
	ordermainDescShopName := ordermainFields[6].Descriptor()
	// ordermain.DefaultShopName holds the default value on creation for the shop_name field.
	ordermain.DefaultShopName = ordermainDescShopName.Default.(string)
	// ordermainDescShipFirstName is the schema descriptor for ship_first_name field.
	ordermainDescShipFirstName := ordermainFields[7].Descriptor()
	// ordermain.DefaultShipFirstName holds the default value on creation for the ship_first_name field.
	ordermain.DefaultShipFirstName = ordermainDescShipFirstName.Default.(string)
	// ordermainDescShipLastName is the schema descriptor for ship_last_name field.
	ordermainDescShipLastName := ordermainFields[8].Descriptor()
	// ordermain.DefaultShipLastName holds the default value on creation for the ship_last_name field.
	ordermain.DefaultShipLastName = ordermainDescShipLastName.Default.(string)
	// ordermainDescShipCompany is the schema descriptor for ship_company field.
	ordermainDescShipCompany := ordermainFields[9].Descriptor()
	// ordermain.DefaultShipCompany holds the default value on creation for the ship_company field.
	ordermain.DefaultShipCompany = ordermainDescShipCompany.Default.(string)
	// ordermainDescShipStreet1 is the schema descriptor for ship_street1 field.
	ordermainDescShipStreet1 := ordermainFields[10].Descriptor()
	// ordermain.DefaultShipStreet1 holds the default value on creation for the ship_street1 field.
	ordermain.DefaultShipStreet1 = ordermainDescShipStreet1.Default.(string)
	// ordermainDescShipStreet2 is the schema descriptor for ship_street2 field.
	ordermainDescShipStreet2 := ordermainFields[11].Descriptor()
	// ordermain.DefaultShipStreet2 holds the default value on creation for the ship_street2 field.
	ordermain.DefaultShipStreet2 = ordermainDescShipStreet2.Default.(string)
	// ordermainDescShipCity is the schema descriptor for ship_city field.
	ordermainDescShipCity := ordermainFields[12].Descriptor()
	// ordermain.DefaultShipCity holds the default value on creation for the ship_city field.
	ordermain.DefaultShipCity = ordermainDescShipCity.Default.(string)
	// ordermainDescShipState is the schema descriptor for ship_state field.
	ordermainDescShipState := ordermainFields[13].Descriptor()
	// ordermain.DefaultShipState holds the default value on creation for the ship_state field.
	ordermain.DefaultShipState = ordermainDescShipState.Default.(string)
	// ordermainDescShipZip is the schema descriptor for ship_zip field.
	ordermainDescShipZip := ordermainFields[14].Descriptor()
	// ordermain.DefaultShipZip holds the default value on creation for the ship_zip field.
	ordermain.DefaultShipZip = ordermainDescShipZip.Default.(string)
	// ordermainDescShipCountry is the schema descriptor for ship_country field.
	ordermainDescShipCountry := ordermainFields[15].Descriptor()
	// ordermain.DefaultShipCountry holds the default value on creation for the ship_country field.
	ordermain.DefaultShipCountry = ordermainDescShipCountry.Default.(string)
	// ordermainDescShipCountryCode is the schema descriptor for ship_country_code field.
	ordermainDescShipCountryCode := ordermainFields[16].Descriptor()
	// ordermain.DefaultShipCountryCode holds the default value on creation for the ship_country_code field.
	ordermain.DefaultShipCountryCode = ordermainDescShipCountryCode.Default.(string)
	// ordermainDescShipPhone is the schema descriptor for ship_phone field.
	ordermainDescShipPhone := ordermainFields[17].Descriptor()
	// ordermain.DefaultShipPhone holds the default value on creation for the ship_phone field.
	ordermain.DefaultShipPhone = ordermainDescShipPhone.Default.(string)
	// ordermainDescShipFax is the schema descriptor for ship_fax field.
	ordermainDescShipFax := ordermainFields[18].Descriptor()
	// ordermain.DefaultShipFax holds the default value on creation for the ship_fax field.
	ordermain.DefaultShipFax = ordermainDescShipFax.Default.(string)
	// ordermainDescShipRemark is the schema descriptor for ship_remark field.
	ordermainDescShipRemark := ordermainFields[19].Descriptor()
	// ordermain.DefaultShipRemark holds the default value on creation for the ship_remark field.
	ordermain.DefaultShipRemark = ordermainDescShipRemark.Default.(string)
	// ordermainDescShipHouse is the schema descriptor for ship_house field.
	ordermainDescShipHouse := ordermainFields[20].Descriptor()
	// ordermain.DefaultShipHouse holds the default value on creation for the ship_house field.
	ordermain.DefaultShipHouse = ordermainDescShipHouse.Default.(string)
	// ordermainDescShipCertificateCode is the schema descriptor for ship_certificate_code field.
	ordermainDescShipCertificateCode := ordermainFields[21].Descriptor()
	// ordermain.DefaultShipCertificateCode holds the default value on creation for the ship_certificate_code field.
	ordermain.DefaultShipCertificateCode = ordermainDescShipCertificateCode.Default.(string)
	// ordermainDescOrderUserEmail is the schema descriptor for order_user_email field.
	ordermainDescOrderUserEmail := ordermainFields[22].Descriptor()
	// ordermain.DefaultOrderUserEmail holds the default value on creation for the order_user_email field.
	ordermain.DefaultOrderUserEmail = ordermainDescOrderUserEmail.Default.(string)
	// ordermainDescCurrency is the schema descriptor for currency field.
	ordermainDescCurrency := ordermainFields[24].Descriptor()
	// ordermain.DefaultCurrency holds the default value on creation for the currency field.
	ordermain.DefaultCurrency = ordermainDescCurrency.Default.(string)
	// ordermainDescCurrenciesID is the schema descriptor for currencies_id field.
	ordermainDescCurrenciesID := ordermainFields[25].Descriptor()
	// ordermain.DefaultCurrenciesID holds the default value on creation for the currencies_id field.
	ordermain.DefaultCurrenciesID = ordermainDescCurrenciesID.Default.(int32)
	// ordermainDescCurrencyRate is the schema descriptor for currency_rate field.
	ordermainDescCurrencyRate := ordermainFields[26].Descriptor()
	// ordermain.DefaultCurrencyRate holds the default value on creation for the currency_rate field.
	ordermain.DefaultCurrencyRate = ordermainDescCurrencyRate.Default.(float64)
	// ordermainDescShippingMethod is the schema descriptor for shipping_method field.
	ordermainDescShippingMethod := ordermainFields[27].Descriptor()
	// ordermain.DefaultShippingMethod holds the default value on creation for the shipping_method field.
	ordermain.DefaultShippingMethod = ordermainDescShippingMethod.Default.(string)
	// ordermainDescShippingMethodOrig is the schema descriptor for shipping_method_orig field.
	ordermainDescShippingMethodOrig := ordermainFields[28].Descriptor()
	// ordermain.DefaultShippingMethodOrig holds the default value on creation for the shipping_method_orig field.
	ordermain.DefaultShippingMethodOrig = ordermainDescShippingMethodOrig.Default.(string)
	// ordermainDescShippingMethodName is the schema descriptor for shipping_method_name field.
	ordermainDescShippingMethodName := ordermainFields[29].Descriptor()
	// ordermain.DefaultShippingMethodName holds the default value on creation for the shipping_method_name field.
	ordermain.DefaultShippingMethodName = ordermainDescShippingMethodName.Default.(string)
	// ordermainDescGrandTotal is the schema descriptor for grand_total field.
	ordermainDescGrandTotal := ordermainFields[30].Descriptor()
	// ordermain.DefaultGrandTotal holds the default value on creation for the grand_total field.
	ordermain.DefaultGrandTotal = ordermainDescGrandTotal.Default.(float64)
	// ordermainDescTrackNumber is the schema descriptor for track_number field.
	ordermainDescTrackNumber := ordermainFields[31].Descriptor()
	// ordermain.DefaultTrackNumber holds the default value on creation for the track_number field.
	ordermain.DefaultTrackNumber = ordermainDescTrackNumber.Default.(string)
	// ordermainDescFollowNumber is the schema descriptor for follow_number field.
	ordermainDescFollowNumber := ordermainFields[32].Descriptor()
	// ordermain.DefaultFollowNumber holds the default value on creation for the follow_number field.
	ordermain.DefaultFollowNumber = ordermainDescFollowNumber.Default.(string)
	// ordermainDescTransactionNumber is the schema descriptor for transaction_number field.
	ordermainDescTransactionNumber := ordermainFields[34].Descriptor()
	// ordermain.DefaultTransactionNumber holds the default value on creation for the transaction_number field.
	ordermain.DefaultTransactionNumber = ordermainDescTransactionNumber.Default.(string)
	// ordermainDescTransactionFee is the schema descriptor for transaction_fee field.
	ordermainDescTransactionFee := ordermainFields[35].Descriptor()
	// ordermain.DefaultTransactionFee holds the default value on creation for the transaction_fee field.
	ordermain.DefaultTransactionFee = ordermainDescTransactionFee.Default.(float64)
	// ordermainDescShippingCost is the schema descriptor for shipping_cost field.
	ordermainDescShippingCost := ordermainFields[38].Descriptor()
	// ordermain.DefaultShippingCost holds the default value on creation for the shipping_cost field.
	ordermain.DefaultShippingCost = ordermainDescShippingCost.Default.(float64)
	// ordermainDescShippingCostExt is the schema descriptor for shipping_cost_ext field.
	ordermainDescShippingCostExt := ordermainFields[39].Descriptor()
	// ordermain.DefaultShippingCostExt holds the default value on creation for the shipping_cost_ext field.
	ordermain.DefaultShippingCostExt = ordermainDescShippingCostExt.Default.(float64)
	// ordermainDescTaxesNumber is the schema descriptor for taxes_number field.
	ordermainDescTaxesNumber := ordermainFields[40].Descriptor()
	// ordermain.DefaultTaxesNumber holds the default value on creation for the taxes_number field.
	ordermain.DefaultTaxesNumber = ordermainDescTaxesNumber.Default.(string)
	// ordermainDescTax is the schema descriptor for tax field.
	ordermainDescTax := ordermainFields[41].Descriptor()
	// ordermain.DefaultTax holds the default value on creation for the tax field.
	ordermain.DefaultTax = ordermainDescTax.Default.(float64)
	// ordermainDescOrderDiscount is the schema descriptor for order_discount field.
	ordermainDescOrderDiscount := ordermainFields[42].Descriptor()
	// ordermain.DefaultOrderDiscount holds the default value on creation for the order_discount field.
	ordermain.DefaultOrderDiscount = ordermainDescOrderDiscount.Default.(float64)
	// ordermainDescInsurance is the schema descriptor for insurance field.
	ordermainDescInsurance := ordermainFields[43].Descriptor()
	// ordermain.DefaultInsurance holds the default value on creation for the insurance field.
	ordermain.DefaultInsurance = ordermainDescInsurance.Default.(float64)
	// ordermainDescOrderWeight is the schema descriptor for order_weight field.
	ordermainDescOrderWeight := ordermainFields[44].Descriptor()
	// ordermain.DefaultOrderWeight holds the default value on creation for the order_weight field.
	ordermain.DefaultOrderWeight = ordermainDescOrderWeight.Default.(float64)
	// ordermainDescOrderType is the schema descriptor for order_type field.
	ordermainDescOrderType := ordermainFields[46].Descriptor()
	// ordermain.DefaultOrderType holds the default value on creation for the order_type field.
	ordermain.DefaultOrderType = ordermainDescOrderType.Default.(int8)
	// ordermainDescSubOrdersCode is the schema descriptor for sub_orders_code field.
	ordermainDescSubOrdersCode := ordermainFields[48].Descriptor()
	// ordermain.DefaultSubOrdersCode holds the default value on creation for the sub_orders_code field.
	ordermain.DefaultSubOrdersCode = ordermainDescSubOrdersCode.Default.(string)
	// ordermainDescWarehouseID is the schema descriptor for warehouse_id field.
	ordermainDescWarehouseID := ordermainFields[51].Descriptor()
	// ordermain.DefaultWarehouseID holds the default value on creation for the warehouse_id field.
	ordermain.DefaultWarehouseID = ordermainDescWarehouseID.Default.(string)
	// ordermainDescOrderListType is the schema descriptor for order_list_type field.
	ordermainDescOrderListType := ordermainFields[52].Descriptor()
	// ordermain.DefaultOrderListType holds the default value on creation for the order_list_type field.
	ordermain.DefaultOrderListType = ordermainDescOrderListType.Default.(int8)
	// ordermainDescOrderBatchNo is the schema descriptor for order_batch_no field.
	ordermainDescOrderBatchNo := ordermainFields[53].Descriptor()
	// ordermain.DefaultOrderBatchNo holds the default value on creation for the order_batch_no field.
	ordermain.DefaultOrderBatchNo = ordermainDescOrderBatchNo.Default.(string)
	// ordermainDescShopID is the schema descriptor for shop_id field.
	ordermainDescShopID := ordermainFields[54].Descriptor()
	// ordermain.DefaultShopID holds the default value on creation for the shop_id field.
	ordermain.DefaultShopID = ordermainDescShopID.Default.(int32)
	// ordermainDescOrderCost is the schema descriptor for order_cost field.
	ordermainDescOrderCost := ordermainFields[57].Descriptor()
	// ordermain.DefaultOrderCost holds the default value on creation for the order_cost field.
	ordermain.DefaultOrderCost = ordermainDescOrderCost.Default.(float64)
	// ordermainDescOrderProfit is the schema descriptor for order_profit field.
	ordermainDescOrderProfit := ordermainFields[58].Descriptor()
	// ordermain.DefaultOrderProfit holds the default value on creation for the order_profit field.
	ordermain.DefaultOrderProfit = ordermainDescOrderProfit.Default.(float64)
	// ordermainDescCommission is the schema descriptor for commission field.
	ordermainDescCommission := ordermainFields[60].Descriptor()
	// ordermain.DefaultCommission holds the default value on creation for the commission field.
	ordermain.DefaultCommission = ordermainDescCommission.Default.(float64)
	// ordermainDescInterceptState is the schema descriptor for intercept_state field.
	ordermainDescInterceptState := ordermainFields[61].Descriptor()
	// ordermain.DefaultInterceptState holds the default value on creation for the intercept_state field.
	ordermain.DefaultInterceptState = ordermainDescInterceptState.Default.(int8)
	// ordermainDescProviderType is the schema descriptor for provider_type field.
	ordermainDescProviderType := ordermainFields[64].Descriptor()
	// ordermain.DefaultProviderType holds the default value on creation for the provider_type field.
	ordermain.DefaultProviderType = ordermainDescProviderType.Default.(int8)
	// ordermainDescOrderPackCost is the schema descriptor for order_pack_cost field.
	ordermainDescOrderPackCost := ordermainFields[65].Descriptor()
	// ordermain.DefaultOrderPackCost holds the default value on creation for the order_pack_cost field.
	ordermain.DefaultOrderPackCost = ordermainDescOrderPackCost.Default.(float64)
	// ordermainDescPaymentFixCost is the schema descriptor for payment_fix_cost field.
	ordermainDescPaymentFixCost := ordermainFields[66].Descriptor()
	// ordermain.DefaultPaymentFixCost holds the default value on creation for the payment_fix_cost field.
	ordermain.DefaultPaymentFixCost = ordermainDescPaymentFixCost.Default.(float64)
	// ordermainDescIsFbaBehalf is the schema descriptor for is_fba_behalf field.
	ordermainDescIsFbaBehalf := ordermainFields[67].Descriptor()
	// ordermain.DefaultIsFbaBehalf holds the default value on creation for the is_fba_behalf field.
	ordermain.DefaultIsFbaBehalf = ordermainDescIsFbaBehalf.Default.(int8)
	// ordermainDescFulfillType is the schema descriptor for fulfill_type field.
	ordermainDescFulfillType := ordermainFields[68].Descriptor()
	// ordermain.DefaultFulfillType holds the default value on creation for the fulfill_type field.
	ordermain.DefaultFulfillType = ordermainDescFulfillType.Default.(int8)
	// ordermainDescFulfillException is the schema descriptor for fulfill_exception field.
	ordermainDescFulfillException := ordermainFields[69].Descriptor()
	// ordermain.DefaultFulfillException holds the default value on creation for the fulfill_exception field.
	ordermain.DefaultFulfillException = ordermainDescFulfillException.Default.(int8)
	// ordermainDescIossNumber is the schema descriptor for ioss_number field.
	ordermainDescIossNumber := ordermainFields[70].Descriptor()
	// ordermain.DefaultIossNumber holds the default value on creation for the ioss_number field.
	ordermain.DefaultIossNumber = ordermainDescIossNumber.Default.(string)
	// ordermainDescSalesRecordNumber is the schema descriptor for sales_record_number field.
	ordermainDescSalesRecordNumber := ordermainFields[72].Descriptor()
	// ordermain.DefaultSalesRecordNumber holds the default value on creation for the sales_record_number field.
	ordermain.DefaultSalesRecordNumber = ordermainDescSalesRecordNumber.Default.(string)
	// ordermainDescTicketCode is the schema descriptor for ticket_code field.
	ordermainDescTicketCode := ordermainFields[73].Descriptor()
	// ordermain.DefaultTicketCode holds the default value on creation for the ticket_code field.
	ordermain.DefaultTicketCode = ordermainDescTicketCode.Default.(string)
	// ordermainDescOverseasWarehouseStatus is the schema descriptor for overseas_warehouse_status field.
	ordermainDescOverseasWarehouseStatus := ordermainFields[74].Descriptor()
	// ordermain.DefaultOverseasWarehouseStatus holds the default value on creation for the overseas_warehouse_status field.
	ordermain.DefaultOverseasWarehouseStatus = ordermainDescOverseasWarehouseStatus.Default.(string)
	// ordermainDescPayPalID is the schema descriptor for pay_pal_id field.
	ordermainDescPayPalID := ordermainFields[75].Descriptor()
	// ordermain.DefaultPayPalID holds the default value on creation for the pay_pal_id field.
	ordermain.DefaultPayPalID = ordermainDescPayPalID.Default.(string)
	// ordermainDescIsUpdate is the schema descriptor for is_update field.
	ordermainDescIsUpdate := ordermainFields[76].Descriptor()
	// ordermain.DefaultIsUpdate holds the default value on creation for the is_update field.
	ordermain.DefaultIsUpdate = ordermainDescIsUpdate.Default.(int8)
	// ordermainDescOrderSaleState is the schema descriptor for order_sale_state field.
	ordermainDescOrderSaleState := ordermainFields[77].Descriptor()
	// ordermain.DefaultOrderSaleState holds the default value on creation for the order_sale_state field.
	ordermain.DefaultOrderSaleState = ordermainDescOrderSaleState.Default.(int8)
	// ordermainDescProductCost is the schema descriptor for product_cost field.
	ordermainDescProductCost := ordermainFields[78].Descriptor()
	// ordermain.DefaultProductCost holds the default value on creation for the product_cost field.
	ordermain.DefaultProductCost = ordermainDescProductCost.Default.(float64)
	// ordermainDescHeadCost is the schema descriptor for head_cost field.
	ordermainDescHeadCost := ordermainFields[79].Descriptor()
	// ordermain.DefaultHeadCost holds the default value on creation for the head_cost field.
	ordermain.DefaultHeadCost = ordermainDescHeadCost.Default.(float64)
	// ordermainDescCarrierCode is the schema descriptor for carrier_code field.
	ordermainDescCarrierCode := ordermainFields[80].Descriptor()
	// ordermain.DefaultCarrierCode holds the default value on creation for the carrier_code field.
	ordermain.DefaultCarrierCode = ordermainDescCarrierCode.Default.(string)
	// ordermainDescWithheldTax is the schema descriptor for withheld_tax field.
	ordermainDescWithheldTax := ordermainFields[81].Descriptor()
	// ordermain.DefaultWithheldTax holds the default value on creation for the withheld_tax field.
	ordermain.DefaultWithheldTax = ordermainDescWithheldTax.Default.(float64)
	// ordermainDescOtherFee is the schema descriptor for other_fee field.
	ordermainDescOtherFee := ordermainFields[82].Descriptor()
	// ordermain.DefaultOtherFee holds the default value on creation for the other_fee field.
	ordermain.DefaultOtherFee = ordermainDescOtherFee.Default.(float64)
	// ordermainDescEscrowTax is the schema descriptor for escrow_tax field.
	ordermainDescEscrowTax := ordermainFields[83].Descriptor()
	// ordermain.DefaultEscrowTax holds the default value on creation for the escrow_tax field.
	ordermain.DefaultEscrowTax = ordermainDescEscrowTax.Default.(float64)
	// ordermainDescFinalProductVatTax is the schema descriptor for final_product_vat_tax field.
	ordermainDescFinalProductVatTax := ordermainFields[84].Descriptor()
	// ordermain.DefaultFinalProductVatTax holds the default value on creation for the final_product_vat_tax field.
	ordermain.DefaultFinalProductVatTax = ordermainDescFinalProductVatTax.Default.(float64)
	// ordermainDescFinalShippingVatTax is the schema descriptor for final_shipping_vat_tax field.
	ordermainDescFinalShippingVatTax := ordermainFields[85].Descriptor()
	// ordermain.DefaultFinalShippingVatTax holds the default value on creation for the final_shipping_vat_tax field.
	ordermain.DefaultFinalShippingVatTax = ordermainDescFinalShippingVatTax.Default.(float64)
	// ordermainDescShippingCharge is the schema descriptor for shipping_charge field.
	ordermainDescShippingCharge := ordermainFields[86].Descriptor()
	// ordermain.DefaultShippingCharge holds the default value on creation for the shipping_charge field.
	ordermain.DefaultShippingCharge = ordermainDescShippingCharge.Default.(float64)
	// ordermainDescVoucherPlatform is the schema descriptor for voucher_platform field.
	ordermainDescVoucherPlatform := ordermainFields[87].Descriptor()
	// ordermain.DefaultVoucherPlatform holds the default value on creation for the voucher_platform field.
	ordermain.DefaultVoucherPlatform = ordermainDescVoucherPlatform.Default.(float64)
	// ordermainDescShippingRebate is the schema descriptor for shipping_rebate field.
	ordermainDescShippingRebate := ordermainFields[89].Descriptor()
	// ordermain.DefaultShippingRebate holds the default value on creation for the shipping_rebate field.
	ordermain.DefaultShippingRebate = ordermainDescShippingRebate.Default.(float64)
	// ordermainDescLabelList is the schema descriptor for label_list field.
	ordermainDescLabelList := ordermainFields[90].Descriptor()
	// ordermain.DefaultLabelList holds the default value on creation for the label_list field.
	ordermain.DefaultLabelList = ordermainDescLabelList.Default.(string)
	// ordermainDescOutRealGrandTotal is the schema descriptor for out_real_grand_total field.
	ordermainDescOutRealGrandTotal := ordermainFields[91].Descriptor()
	// ordermain.DefaultOutRealGrandTotal holds the default value on creation for the out_real_grand_total field.
	ordermain.DefaultOutRealGrandTotal = ordermainDescOutRealGrandTotal.Default.(float64)
	// ordermainDescBillList is the schema descriptor for bill_list field.
	ordermainDescBillList := ordermainFields[92].Descriptor()
	// ordermain.DefaultBillList holds the default value on creation for the bill_list field.
	ordermain.DefaultBillList = ordermainDescBillList.Default.(string)
	// ordermainDescOutGrandTotal is the schema descriptor for out_grand_total field.
	ordermainDescOutGrandTotal := ordermainFields[93].Descriptor()
	// ordermain.DefaultOutGrandTotal holds the default value on creation for the out_grand_total field.
	ordermain.DefaultOutGrandTotal = ordermainDescOutGrandTotal.Default.(float64)
	// ordermainDescDeliverShop is the schema descriptor for deliver_shop field.
	ordermainDescDeliverShop := ordermainFields[94].Descriptor()
	// ordermain.DefaultDeliverShop holds the default value on creation for the deliver_shop field.
	ordermain.DefaultDeliverShop = ordermainDescDeliverShop.Default.(string)
	// ordermainDescShippingCostFinal is the schema descriptor for shipping_cost_final field.
	ordermainDescShippingCostFinal := ordermainFields[95].Descriptor()
	// ordermain.DefaultShippingCostFinal holds the default value on creation for the shipping_cost_final field.
	ordermain.DefaultShippingCostFinal = ordermainDescShippingCostFinal.Default.(float64)
	// ordermainDescShippingFreeAbout is the schema descriptor for shipping_free_about field.
	ordermainDescShippingFreeAbout := ordermainFields[96].Descriptor()
	// ordermain.DefaultShippingFreeAbout holds the default value on creation for the shipping_free_about field.
	ordermain.DefaultShippingFreeAbout = ordermainDescShippingFreeAbout.Default.(float64)
	// ordermainDescCreateOrderStatus is the schema descriptor for create_order_status field.
	ordermainDescCreateOrderStatus := ordermainFields[97].Descriptor()
	// ordermain.DefaultCreateOrderStatus holds the default value on creation for the create_order_status field.
	ordermain.DefaultCreateOrderStatus = ordermainDescCreateOrderStatus.Default.(int8)
	// ordermainDescIsQcc is the schema descriptor for is_qcc field.
	ordermainDescIsQcc := ordermainFields[99].Descriptor()
	// ordermain.DefaultIsQcc holds the default value on creation for the is_qcc field.
	ordermain.DefaultIsQcc = ordermainDescIsQcc.Default.(int8)
	// ordermainDescRejectReason is the schema descriptor for reject_reason field.
	ordermainDescRejectReason := ordermainFields[100].Descriptor()
	// ordermain.DefaultRejectReason holds the default value on creation for the reject_reason field.
	ordermain.DefaultRejectReason = ordermainDescRejectReason.Default.(string)
	// ordermainDescDiscountCode is the schema descriptor for discount_code field.
	ordermainDescDiscountCode := ordermainFields[102].Descriptor()
	// ordermain.DefaultDiscountCode holds the default value on creation for the discount_code field.
	ordermain.DefaultDiscountCode = ordermainDescDiscountCode.Default.(string)
	// ordermainDescStockoutStatus is the schema descriptor for stockout_status field.
	ordermainDescStockoutStatus := ordermainFields[103].Descriptor()
	// ordermain.DefaultStockoutStatus holds the default value on creation for the stockout_status field.
	ordermain.DefaultStockoutStatus = ordermainDescStockoutStatus.Default.(int8)
	// ordermainDescOrderLength is the schema descriptor for order_length field.
	ordermainDescOrderLength := ordermainFields[104].Descriptor()
	// ordermain.DefaultOrderLength holds the default value on creation for the order_length field.
	ordermain.DefaultOrderLength = ordermainDescOrderLength.Default.(float64)
	// ordermainDescOrderWidth is the schema descriptor for order_width field.
	ordermainDescOrderWidth := ordermainFields[105].Descriptor()
	// ordermain.DefaultOrderWidth holds the default value on creation for the order_width field.
	ordermain.DefaultOrderWidth = ordermainDescOrderWidth.Default.(float64)
	// ordermainDescOrderHeight is the schema descriptor for order_height field.
	ordermainDescOrderHeight := ordermainFields[106].Descriptor()
	// ordermain.DefaultOrderHeight holds the default value on creation for the order_height field.
	ordermain.DefaultOrderHeight = ordermainDescOrderHeight.Default.(float64)
	// ordermainDescFirstSide is the schema descriptor for first_side field.
	ordermainDescFirstSide := ordermainFields[107].Descriptor()
	// ordermain.DefaultFirstSide holds the default value on creation for the first_side field.
	ordermain.DefaultFirstSide = ordermainDescFirstSide.Default.(float64)
	// ordermainDescSecondSide is the schema descriptor for second_side field.
	ordermainDescSecondSide := ordermainFields[108].Descriptor()
	// ordermain.DefaultSecondSide holds the default value on creation for the second_side field.
	ordermain.DefaultSecondSide = ordermainDescSecondSide.Default.(float64)
	// ordermainDescThirdSide is the schema descriptor for third_side field.
	ordermainDescThirdSide := ordermainFields[109].Descriptor()
	// ordermain.DefaultThirdSide holds the default value on creation for the third_side field.
	ordermain.DefaultThirdSide = ordermainDescThirdSide.Default.(float64)
	// ordermainDescOrderFeeWeight is the schema descriptor for order_fee_weight field.
	ordermainDescOrderFeeWeight := ordermainFields[110].Descriptor()
	// ordermain.DefaultOrderFeeWeight holds the default value on creation for the order_fee_weight field.
	ordermain.DefaultOrderFeeWeight = ordermainDescOrderFeeWeight.Default.(float64)
	// ordermainDescShopManager is the schema descriptor for shop_manager field.
	ordermainDescShopManager := ordermainFields[111].Descriptor()
	// ordermain.DefaultShopManager holds the default value on creation for the shop_manager field.
	ordermain.DefaultShopManager = ordermainDescShopManager.Default.(string)
	// ordermainDescPushStatus is the schema descriptor for push_status field.
	ordermainDescPushStatus := ordermainFields[112].Descriptor()
	// ordermain.DefaultPushStatus holds the default value on creation for the push_status field.
	ordermain.DefaultPushStatus = ordermainDescPushStatus.Default.(int8)
}
